### ISSUE TITLE
Missing `keep_these_glyphs` function?

### ISSUE THREAD

**Issue by kevincon** [AceLewis/fontcrusher#1]
I'm trying to crush a font using your library with the following code:

```
glyphs_to_keep = fontcrusher.get_glyphs_from_file(GLYPH_WHITE_LIST_FILE)
crushed_font = fontcrusher.load_and_crush_font(FONT_FILE, glyphs_to_keep)
```

but I'm getting this error:

```
File "/usr/local/lib/python2.7/site-packages/fontcrusher/fontcrusher.py", line 19, in load_and_crush_font
    return keep_these_glyphs(original_font, glyphs)
```

Looking at the source code for `fontcrusher`, I can't find where `keep_these_glyphs()` is defined. It doesn't seem to be provided by `fonttools` either. Where should I get that function?

**Comment by AceLewis** [comment]
This is due to renaming the keep_these_glyphs to crush_font when making this. I will fix this when I next get on my PC, load_and_crush_font is just supposed to load the font then use the function to crush it.

For the mean time you can just load the font then use the crush_font function seperatly like what load_and_crush_font should do.

**Comment by AceLewis** [comment]
I have now fixed this issue in https://github.com/AceLewis/fontcrusher/commit/09f940bf1b61db0a4c9fc188a7155f4198985506
